### ISSUE TITLE
Add a date to previous history of TB

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/uclp-tb#215]
record created by history of TB in the timeline

**Comment by davidmiller** [comment]
Is this done? I can't see it happening :(

**Comment by fredkingham** [comment]
we don't actually have a date for the previous tb infection, at the moment its a char field. We could rejig it and ask for the year, then maybe the month if was in the last 5 years or something.

Needs thought

**Comment by fredkingham** [comment]
We're going to enter in the clinical interaction where it was reported that the person had a previous history of tb
