### ISSUE TITLE
As a User I want to record the absence of some symptoms

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/uclp-tb#32]
So that I can be sure that we asked the question - because the absence of things is explicitly clinically significant for TB.

Acceptance criteria: 

- [ ] Updated symptoms form & controller that lets me set major TB symptoms quickly and easily
- [ ] recording Y/N for these symptoms as a risk factor
- [ ] But also recording any arbitrary symptom

**Comment by fredkingham** [comment]
we're going to have a seperate model that also updates the symptoms complex when you click in the check box. Removal of symptoms in the complex will cause no change in the check box at this time
