### ISSUE TITLE
As a User I need to enter the details of the screening appointment

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/uclp-tb#6]
- [ ] add stage to episode, stages should be defined in the episode type
-  [ ] add a button to the detail view that pathway in a different page
 - [x] risks
 - [x] microbiology test
 - [ ] BCG
 -  [ ] Referral risks

- [ ] modal pathway should add you to the next episode stage

**Comment by davidmiller** [comment]
Done for now - individual bugs only from here
